name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Получение исходного кода
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Настройка Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Установка зависимостей
      - name: Install dependencies
        run: npm install

      # 4. Сборка приложения
      - name: Build application
        run: npm run build

      # 5. Сборка Docker-образа
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nest-tasks-opt:latest .

      # 6. Логин в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7. Push образа в Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nest-tasks-opt:latest

      # 8. Деплой на Heroku
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
