name: CI/CD Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Получение исходного кода
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Настройка Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Установка зависимостей
      - name: Install dependencies
        run: npm install

      # 4. Сборка приложения
      - name: Build application
        run: npm run build

      # 5. Логин в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Сборка Docker-образа
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nest-tasks-opt:latest .

      # 7. Push образа в Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nest-tasks-opt:latest

      # 8. Триггер деплоя на Render
      - name: Trigger Render Deploy
        run: |
          curl -X POST https://api.render.com/deploy/srv-d4c5ilf5r7bs73a6s09g